### ISSUE TITLE
system does not support AArch32

### ISSUE THREAD

**Issue by wadecong** [anbox-cloud/cloud-gaming-demo#22]
```
ubuntu@wille22:~$ amc application show cdctngeocg60234a7pd0
id: cdce70k8s19g22tq9720
name: bombsquad
status: error
published: false
immutable: false
inhibit-auto-updates: false
tags: []
parent-image: jammy:android12:arm64
abi: arm64-v8a
config:
  instance-type: a4.3
  boot-package: net.froemling.bombsquad
versions:
  0:
    image: jammy:android12:arm64 (version 0)
    published: false
    status: error
    extra-data: {}
    error_message: system does not support AArch32
    video-encoder: gpu-preferred
    watchdog:
      disabled: false
      allowed-packages: []
```
